In [2]:
from sklearn.decomposition import PCA
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.metrics import accuracy_score, confusion_matrix, matthews_corrcoef


tf.keras.utils.set_random_seed(42)


In [3]:
def one_hot_encode(seq, vocab):
    """One-hot encode a sequence based on a given vocabulary."""
    one_hot = np.zeros((len(seq), len(vocab)), dtype=np.float32)
    for i, char in enumerate(seq):
        if char in vocab:
            one_hot[i, vocab.index(char)] = 1.0
    return one_hot

# Define your vocabularies
aa_vocab = 'ACDEFGHIKLMNPQRSTVWY_'  # 20 amino acids + 1 for gap/unknown
structure_vocab = 'he_'  # h for helix, e for sheet, _ for coil


def prepare_data(filepath, window_size=13):
    sequences = []
    structures = []
    current_seq = []
    current_struct = []
    processing_sequence = False  # Track when inside a sequence block

    with open(filepath, 'r') as file:
        for line in file:
            line = line.strip()
            if line == '<>':  # Toggle processing flag
                if processing_sequence:  # We are ending a sequence block
                    if current_seq and current_struct:
                        seq_encoded = one_hot_encode(current_seq, aa_vocab)
                        struct_encoded = one_hot_encode(current_struct, structure_vocab)

                        # Apply sliding window
                        for i in range(len(seq_encoded) - window_size + 1):
                            window = seq_encoded[i:i + window_size]
                            label = struct_encoded[i + window_size // 2]
                            sequences.append(window)
                            structures.append(label)

                    current_seq = []
                    current_struct = []
                processing_sequence = not processing_sequence
                continue

            elif 'end' in line:  # Generalized handling for any 'end' marker
                continue  # Just skip this line, do not end processing sequence

            if processing_sequence:
                parts = line.split()
                if len(parts) != 2:
                    continue  # Skip malformed lines or lines that do not fit expected format
                current_seq.append(parts[0])
                current_struct.append(parts[1])

    return np.array(sequences), np.array(structures)


def prepare_data_for_svm(filepath, window_size=13):
    sequences, structures = prepare_data(filepath, window_size)
    # Flatten the windows for SVM processing
    flat_sequences = sequences.reshape(sequences.shape[0], -1)  # Reshape to (number_of_samples, window_size*features_per_aa)
    
    return flat_sequences, structures

In [7]:

# Example paths, replace with your actual file pathsin
train_path = 'Q_and_s_data/protein-secondary-structure.train.txt'
test_path = 'Q_and_s_data/protein-secondary-structure.test.txt'

x_train, y_train = prepare_data_for_svm(train_path)
x_test, y_test = prepare_data_for_svm(test_path)

In [8]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(8110, 273) (8110, 3)
(1714, 273) (1714, 3)


In [19]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, matthews_corrcoef, confusion_matrix

# Assuming x_train and y_train are your input and labels loaded from your function
# Flatten the one-hot encoded labels to a single dimension
y_train_flat = np.argmax(y_train, axis=1)
y_test_flat = np.argmax(y_test, axis=1)

# Scaling the data
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train.reshape(x_train.shape[0], -1))
x_test_scaled = scaler.transform(x_test.reshape(x_test.shape[0], -1))

# Initialize and train the SVM
svm_model = SVC(kernel='rbf', C=2.0, gamma='auto', random_state=42, verbose=True)
svm_model.fit(x_train_scaled, y_train_flat)

# Predict on test data
y_pred = svm_model.predict(x_test_scaled)

# Compute metrics
q3_score = accuracy_score(y_test_flat, y_pred)
cm = confusion_matrix(y_test_flat, y_pred)

print()
print(f"Q3 Score (Accuracy): {q3_score:.4f}")
print("Confusion Matrix:\n", cm)

# Helper function to calculate MCC for each class
def calculate_mcc_for_each_class(y_true, y_pred, num_classes):
    mcc_scores = []
    for class_id in range(num_classes):
        # Create binary labels for the current class
        y_true_binary = (y_true == class_id).astype(int)
        y_pred_binary = (y_pred == class_id).astype(int)
        
        # Calculate MCC and append to results
        mcc = matthews_corrcoef(y_true_binary, y_pred_binary)
        mcc_scores.append(mcc)
    
    return mcc_scores

# Calculate MCC for each class
mcc_scores = calculate_mcc_for_each_class(y_test_flat, y_pred, 3)

# Print the MCC for each class
class_labels = ['Helix', 'Sheet', 'Coil']
for label, mcc in zip(class_labels, mcc_scores):
    print(f"MCC for {label}: {mcc:.4f}")


[LibSVM]
Q3 Score (Accuracy): 0.6324
Confusion Matrix:
 [[199  25 211]
 [ 69 111 146]
 [117  62 774]]
MCC for Helix: 0.3254
MCC for Sheet: 0.3411
MCC for Coil: 0.3598
